### PR TITLE
Release/3.6.0 tumour alt copies tumour ref copies graphkb 1.8.0

### PR DESCRIPTION
**Pull request by dustinbleile**
Release 3.6.0
    New Features:
     - new IPR details for SMALL_MUT_OPTIONAL variants; added tumourAltCopies and tumourRefCopies
    Improvements
     - Uses pori_graphkb_python 1.8.0 features for consistency:
       - use function get_therapeutic_associated_genes from pori_graphkb_python.
       - STATEMENT_RETURN_PROPERTIES constant from pori_graphkb_python.
     - Update TERT promoter test - use standard hgvsCds notation 'TERT:c.-124C>T'

### CODE REVIEW

**Review by calchoo — APPROVED** [review]

**Comment by dustinbleile** [comment]
Hi @creisle,
I'm not sure why the python checks just started failing now.

It looks almost like support for python 3.6 checks was dropped?

**Comment by dustinbleile** [comment]
looks like this is part of the build test problems?

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2
```
https://github.com/actions/runner-images/issues/6399

**Comment by mattdoug604** [comment]
@dustinbleile looks like the build is no longer failing, but one of the test are: https://github.com/bcgsc/pori_ipr_python/actions/runs/3661596222/jobs/6189940973#step:7:1135

**Review by mattdoug604 — APPROVED** [review]

**Comment by dustinbleile** [comment]
Hi @creisle,

How do we remove the 'build (3.6) Expected — Waiting for status to be reported' requirement for release?
It doesn't seem like github is supporting python 3.6 anymore

**Comment by creisle** [comment]
> Hi @creisle,
> 
> How do we remove the 'build (3.6) Expected — Waiting for status to be reported' requirement for release? It doesn't seem like github is supporting python 3.6 anymore

Looks like the actions were out of date, removed 3.6 and added the higher 3.Xs that were already running

**Pull request merged**
