### PR TITLE
Release/v3.5.0

### PR DESCRIPTION
**Pull request by mattdoug604**
Release v3.5.0

Features:
* GERO-289 - 'iprEvidenceLevel'
* SDEV-3122 - annotate_positional_variants - match all hgvs notations given
* SDEV-3148 - speed up query for gene information by filtering on gene lists
* improve custom_kb_match_filter logging details

Bugfixes:
* GERO-289 - use create_graphkb_sv_notation in summary.py to force consistent fusion representations
* GERO-289 - create_graphkb_sv_notation replace 'removesuffix' with python<3.8 compatible code
* GERO-299 - capture and remove matches to conflicting missense and nonsense mutations
* SDEV-3122 - Drop duplicate alterations using a Hashabledict

Changes:
* refactor, typing updates to reduce linting errors

### CODE REVIEW

**Comment by mathieulemieux** [comment]
Hi @mattdoug604 , should IPR Evidence levels be added to the description's features or this functionality is not fully implemented yet?

**Comment by mattdoug604** [comment]
> Hi @mattdoug604 , should IPR Evidence levels be added to the description's features or this functionality is not fully implemented yet?

Yes it should. I updated the description.

**Review by mathieulemieux — APPROVED** [review]
I ran the test suite with success and did an overall visual review.
I don't have access to any script or program that use the ipr python module so I didn't test its behavior beyond that though.

**Review by dustinbleile — APPROVED** [review]
Tested this version successfully with the current gsc_report develop branch.

**Comment by mattdoug604** [comment]
Added @dustinbleile's latest changes (https://github.com/bcgsc/pori_ipr_python/pull/94) to this release.

**Review by dustinbleile — APPROVED** [review]

**Review by Nithriel — APPROVED** [review]

**Review by elewis2 — APPROVED** [review]

**Pull request merged**
